apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-app-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-app-mongo
  template:
    metadata:
      labels:
        app: blog-app-mongo
    spec:
      containers:
        - name: mongo
          image: sen987/mongo:latest
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-volume
              mountPath: /data/db
      volumes:
        - name: mongo-volume
          emptyDir: {}
