apiVersion: v1
kind: Service
metadata:
  name: blog-app-react-client
spec:
  selector:
    app: blog-app-react-client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5173
  type: LoadBalancer
