apiVersion: v1
kind: Service
metadata:
  name: blog-app-node-server
spec:
  selector:
    app: blog-app-node-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
